version: '3.6'
services:
  treinamento:
    container_name: treinamento
    environment: 
      XDEBUG_HOST: ${XDEBUG_HOST}
    command: 
      bash -c "start-container"
    build: .
    volumes: 
      - ./src:/var/www/treinamento
    ports:
      - 80:80